### ISSUE TITLE
Fix an Ansible script to install Consul

### ISSUE THREAD

**Issue by PierreMesure** [digidemlab/consul-ansible#2]
# TO-DO:

## Server
- [ ] Provision a VPS

## External services
- [ ] Request a token from Sentry
- [ ] Request a token from Matomo
- [ ] Request specific STMP credentials (optional)

## Linux
- [X] `apt-upgrade`
- [X] Set timezone
- [X] Create Linux user

## Database
- [X] Install Postgres
- [ ] Install Redis

## Dependencies
- [X] Install rvm
- [X] Install Ruby
- [X] Install Bundler
- [X] Install NodeJS
- [X] Install Nginx
- [ ] Install Sidekiq

## Consul 
- [X] Checkout Consul from repo
- [X] Install gems
- [ ] Install Figaro
- [ ] Import env variables with Figaro
- [X] Precompile assets
- [X] Create database for Consul
- [X] Create table structure for database
- [X] Create basic seeds

## Security
- [X] Set up SSL certificate (with Let's encrypt or private key)

## Other
- [ ] Schedule file and DB backups
- [ ] Set up Matomo for analytics
